alias -s {js,json,yaml,html,css,toml}='bat'
alias -s md='glow'
alias -s git='git clone'

alias -g G='| rga --hyperlink-format=kitty'

alias cat='bat'
alias co='checkout_branch'
alias cfg='cd ~/.config/nvim && vi'
alias cp='cp -v'
alias dirs='dirs -v'
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias dots='dotfiles'
alias f='fzf | xargs -I{} nvim {}'
alias fif='find_in_file'
alias fim='find_files_with_multiple'
alias fzf='fzf --preview "([[ -f {} ]] && (bat --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200"'
alias g='git'
alias gdm='git branch --merged | grep -v "\*" | xargs -n 1 git branch -d'
alias gnc='ga && new-commit'
alias grep='rga --hyperlink-format=kitty'
alias ip='ip --color=auto'
alias rg='rga --hyperlink-format=kitty'
alias k='kubectl'
alias l='eza -lbha -o --icons --group-directories-first --hyperlink --color-scale=size' # list, size, type, git
alias less='bat'
alias lg='lazygit'
alias lt='eza -TlbFha --git --icons --group-directories-first --level=2'
alias mv='mv -v'
alias pip='pip3'
alias py='python3'
alias python='python3'
alias rm='rm -v'
alias rsync='rsync -az --info=progress2'
alias spec='bundle exec rspec'
alias shutdown='sudo shutdown -h now'
alias sudo='sudo '
alias tf='terraform'
alias update='update_global_packages'
alias updatep10k='git -C $ZSH_CUSTOM/themes/powerlevel10k pull'
alias vi='nvim'
alias vim='nvim'
