#!/bin/sh

# TODO: make this work better

# red=$(tput setaf 1)
# yellow=$(tput setaf 3)
# reset=$(tput sgr0)
# div="\n${yellow}******************${reset}\n"
# echo 'running post-checkout hook'
# grep_diff() {
#   git diff --name-only HEAD@{1} HEAD| rg '$1'
#   echo 'found it '
# }
#
# gemfile=$(fd --max-depth 2 Gemfile)
#
# if [ -n "$gemfile" ] && command -v bundle >/dev/null &&
#   git diff --name-only HEAD@{1} HEAD| rg 'Gemfile'
# then
#   msg="${red}YOUR RUBY BUNDLES COULD BE OUT OF DATE. RUN \"bundle install\".${reset}"
#   (echo "$div$msg$div")
#   # (unset GIT_DIR; exec bundle check || exec bundle install)
#   true
# fi
#
# node_msg="${red}YOUR NODE MODULES COULD BE OUT OF DATE. RUN ${reset}"
#
# package_json=$(fd package.json --max-depth 2)
# package_lock=$(fd package-lock.json --max-depth 2)
# yarn_lock=$(fd yarn.lock  --max-depth 1)
#
# if [ -n "$package_json" ] &&
#   grep_diff 'package.json'
#   # git diff --name-only HEAD@{1} HEAD | rg 'package.json'
# then
#   (echo "$div$node_msg$msg$div")
# # find . -iname package.json ! -path '*/node_modules/*' -exec yarn --cwd "{} | dirname" ';'
#   true
# # elif [ -f "$package_lock" ] && command -v npm >/dev/null &&
# #   git diff --name-only HEAD@{1} HEAD | grep -q -e '^package\.json$'
# # then
# #   msg="${yellow}\"npm install\".${reset}"
# #   (echo "$div$node_msg$msg$div")
# #   true
# fi
