[user]
name = "Blaine Venturine"
email = "blaineventurine@gmail.com"

[diff]
tool = "diffnav"

[diff.git]
context = 10

[ui]
diff-formatter = ":git"
pager = ["delta", "--pager", "less -FRX"]
default-command = "log"
editor = "nvim"
diff-context = 10

[[--scope]]
--when.commands = ["diff", "show"]

[--scope.ui]
pager = "diffnav"

[signing]
signing-behavior = "own" 
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[git]
# Automatically import/export from git
auto-local-bookmark = true
